### ISSUE TITLE
GoLive Activities Checklist - MackTrucks BO

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-bo#8]
Checklist of all activities needed for the GoLive of MackTrucks BO:

**Preparation tasks**
- [x] #1 

**Pre, during, and post-GoLive:**
- [x] #2 

**Pre-GoLive:**
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [ ] [AEM GoLive steps](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- Legacy redirects
- Favicon
- CDN configuration
- Update production host

**Post-GoLive:**
- [ ] [AEM Post-GoLive Validation](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- 404 Report

**Comment by Kannan-CM** [comment]
Content migrated and site is live
